db:
  image: mariadb:latest
  expose:
    - 3306
  volumes:
    - /var/lib/data
  environment:
    MYSQL_DATABASE: 'db'
    MYSQL_USER: 'admin'
    MYSQL_PASSWORD: 'pass'
    MYSQL_ROOT_PASSWORD: 'root'
  ports:
    - '3306:3306'
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

web:
  build: .
  ports:
    - '80'
    - '22'
  links:
    - db:db
  volumes:
    - /data
  environment:
    - GITHUB_REPOSITORY=https://github.com/TYPO3/TYPO3.CMS.BaseDistribution.git
    - GITHUB_USERNAME=yourgithubusername
    - VIRTUAL_HOST=dev.typo3.local